import { ipcMain } from 'electron'
import { join } from 'path'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs'

function getServerDataPath(dataPath: string): string {
  // Expand %USERPROFILE% on Windows
  return dataPath.replace('%USERPROFILE%', process.env.USERPROFILE || process.env.HOME || '')
}

function getServerDir(dataPath: string): string {
  return join(getServerDataPath(dataPath), 'Server')
}

export function setupFileHandlers() {
  // Read .ini file
  ipcMain.handle('config:readIni', async (_event, serverName: string, dataPath: string) => {
    try {
      const serverDir = getServerDir(dataPath)
      const iniPath = join(serverDir, `${serverName}.ini`)

      if (!existsSync(iniPath)) {
        return { success: true, settings: {}, exists: false }
      }

      const content = readFileSync(iniPath, 'utf-8')
      const settings = parseIni(content)
      return { success: true, settings, exists: true }
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : String(error)
      return { success: false, message: msg }
    }
  })

  // Write .ini file
  ipcMain.handle('config:writeIni', async (_event, serverName: string, dataPath: string, settings: Record<string, unknown>) => {
    try {
      const serverDir = getServerDir(dataPath)
      if (!existsSync(serverDir)) {
        mkdirSync(serverDir, { recursive: true })
      }

      const iniPath = join(serverDir, `${serverName}.ini`)
      const content = serializeIni(settings)
      writeFileSync(iniPath, content, 'utf-8')
      return { success: true }
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : String(error)
      return { success: false, message: msg }
    }
  })

  // Read SandboxVars.lua
  ipcMain.handle('config:readSandbox', async (_event, serverName: string, dataPath: string) => {
    try {
      const serverDir = getServerDir(dataPath)
      const luaPath = join(serverDir, `${serverName}_SandboxVars.lua`)

      if (!existsSync(luaPath)) {
        return { success: true, settings: {}, exists: false }
      }

      const content = readFileSync(luaPath, 'utf-8')
      const settings = parseSandboxLua(content)
      return { success: true, settings, exists: true }
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : String(error)
      return { success: false, message: msg }
    }
  })

  // Write SandboxVars.lua
  ipcMain.handle('config:writeSandbox', async (_event, serverName: string, dataPath: string, settings: Record<string, unknown>) => {
    try {
      const serverDir = getServerDir(dataPath)
      if (!existsSync(serverDir)) {
        mkdirSync(serverDir, { recursive: true })
      }

      const luaPath = join(serverDir, `${serverName}_SandboxVars.lua`)
      const content = serializeSandboxLua(settings)
      writeFileSync(luaPath, content, 'utf-8')
      return { success: true }
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : String(error)
      return { success: false, message: msg }
    }
  })
}

function parseIni(content: string): Record<string, unknown> {
  const result: Record<string, unknown> = {}
  const lines = content.split('\n')

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith(';')) continue

    const eqIdx = trimmed.indexOf('=')
    if (eqIdx === -1) continue

    const key = trimmed.substring(0, eqIdx).trim()
    const value = trimmed.substring(eqIdx + 1).trim()

    // Parse value types
    if (value.toLowerCase() === 'true') result[key] = true
    else if (value.toLowerCase() === 'false') result[key] = false
    else if (!isNaN(Number(value)) && value !== '') result[key] = Number(value)
    else result[key] = value
  }

  return result
}

function serializeIni(settings: Record<string, unknown>): string {
  const lines: string[] = [
    '# Project Zomboid Server Configuration',
    '# Generated by PZ Server Manager',
    '',
  ]

  for (const [key, value] of Object.entries(settings)) {
    if (value === null || value === undefined) continue
    lines.push(`${key}=${value}`)
  }

  return lines.join('\n') + '\n'
}

function parseSandboxLua(content: string): Record<string, unknown> {
  const result: Record<string, unknown> = {}

  // Parse top-level SandboxVars = { ... }
  const mainMatch = content.match(/SandboxVars\s*=\s*\{([\s\S]*)\}/)
  if (!mainMatch) return result

  const body = mainMatch[1]
  parseluaTable(body, result)

  return result
}

function parseluaTable(body: string, result: Record<string, unknown>) {
  // Match key = value pairs (not nested tables)
  const lines = body.split('\n')
  let inZombieConfig = false
  const zombieConfig: Record<string, unknown> = {}

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('--')) continue

    if (trimmed.includes('ZombieConfig') && trimmed.includes('{')) {
      inZombieConfig = true
      continue
    }

    if (inZombieConfig) {
      if (trimmed === '}' || trimmed === '},') {
        inZombieConfig = false
        result['ZombieConfig'] = zombieConfig
        continue
      }
      const match = trimmed.match(/^(\w+)\s*=\s*(.+?)(?:\s*--.*)?[,]?$/)
      if (match) {
        zombieConfig[match[1]] = parseluaValue(match[2].trim())
      }
      continue
    }

    const match = trimmed.match(/^(\w+)\s*=\s*(.+?)(?:\s*--.*)?[,]?$/)
    if (match) {
      result[match[1]] = parseluaValue(match[2].trim())
    }
  }
}

function parseluaValue(val: string): unknown {
  const v = val.replace(/,$/, '').trim()
  if (v === 'true') return true
  if (v === 'false') return false
  if (!isNaN(Number(v))) return Number(v)
  if (v.startsWith('"') && v.endsWith('"')) return v.slice(1, -1)
  return v
}

function serializeSandboxLua(settings: Record<string, unknown>): string {
  const lines: string[] = [
    '-- Project Zomboid Sandbox Configuration',
    '-- Generated by PZ Server Manager',
    '',
    'SandboxVars = {',
  ]

  const zombieConfig = settings['ZombieConfig'] as Record<string, unknown> | undefined

  for (const [key, value] of Object.entries(settings)) {
    if (key === 'ZombieConfig') continue
    if (value === null || value === undefined) continue

    if (typeof value === 'boolean') {
      lines.push(`    ${key} = ${value},`)
    } else if (typeof value === 'number') {
      lines.push(`    ${key} = ${value},`)
    } else if (typeof value === 'string') {
      lines.push(`    ${key} = "${value}",`)
    } else {
      lines.push(`    ${key} = ${value},`)
    }
  }

  if (zombieConfig) {
    lines.push('    ZombieConfig = {')
    for (const [key, value] of Object.entries(zombieConfig)) {
      if (value === null || value === undefined) continue
      if (typeof value === 'boolean') {
        lines.push(`        ${key} = ${value},`)
      } else if (typeof value === 'number') {
        lines.push(`        ${key} = ${value},`)
      } else {
        lines.push(`        ${key} = ${value},`)
      }
    }
    lines.push('    },')
  }

  lines.push('}')
  return lines.join('\n') + '\n'
}
