import { ipcMain, BrowserWindow } from 'electron'
import { spawn, exec, ChildProcess } from 'child_process'
import { join } from 'path'
import { existsSync, writeFileSync, mkdirSync, readFileSync } from 'fs'
import { getProfile } from './profileManager'

interface ServerProcess {
  watcher: NodeJS.Timeout | null
  pid: number | null
  status: 'starting' | 'running' | 'stopping' | 'stopped'
  startTime: Date
  serverName: string
  serverDir: string
}

const runningServers = new Map<string, ServerProcess>()
let mainWindowRef: BrowserWindow | null = null

// ---------------------------------------------------------------------------
// Resolve the Zomboid data directory (where Server/ and Saves/ live)
// ---------------------------------------------------------------------------
function resolveDataPath(worldSavePath?: string): string {
  const raw = worldSavePath || '%USERPROFILE%\\Zomboid'
  return raw.replace(/%USERPROFILE%/gi, process.env.USERPROFILE || process.env.HOME || '')
}

// ---------------------------------------------------------------------------
// Write a complete INI file for this profile to the Zomboid\Server folder.
// Merges all profile settings so PZ sees a fully-populated config.
// ---------------------------------------------------------------------------
function writeProfileIni(
  serverName: string,
  dataPath: string,
  profile: Awaited<ReturnType<typeof getProfile>>
): void {
  if (!profile) return
  const serverDir = join(dataPath, 'Server')
  if (!existsSync(serverDir)) mkdirSync(serverDir, { recursive: true })

  const iniPath = join(serverDir, `${serverName}.ini`)

  // Build the complete settings object: stored iniSettings + top-level profile fields
  const settings: Record<string, unknown> = {
    ...(profile.iniSettings || {}),
    // Always override these from the profile so they stay in sync
    DefaultPort: profile.port,
    UDPPort: profile.udpPort,
    MaxPlayers: profile.maxPlayers,
    Password: profile.serverPassword || '',
    // Mod lists from the mods array
    WorkshopItems: profile.mods.map(m => m.workshopId).filter(Boolean).join(';'),
    Mods: profile.mods.map(m => m.modId).filter(Boolean).join(';'),
  }

  const lines: string[] = [
    '# Project Zomboid Server Configuration',
    `# Profile: ${profile.name}`,
    '# Generated by PZ Server Manager — do not edit manually while server is running',
    '',
  ]
  for (const [key, value] of Object.entries(settings)) {
    if (value === null || value === undefined) continue
    lines.push(`${key}=${value}`)
  }

  writeFileSync(iniPath, lines.join('\n') + '\n', 'utf-8')
}

// ---------------------------------------------------------------------------
// Write a complete SandboxVars.lua for this profile.
// ---------------------------------------------------------------------------
function writeProfileSandbox(
  serverName: string,
  dataPath: string,
  profile: Awaited<ReturnType<typeof getProfile>>
): void {
  if (!profile) return
  const serverDir = join(dataPath, 'Server')
  if (!existsSync(serverDir)) mkdirSync(serverDir, { recursive: true })

  const luaPath = join(serverDir, `${serverName}_SandboxVars.lua`)
  const settings = profile.sandboxSettings || {}
  const zombieConfig = (settings.ZombieConfig as Record<string, unknown>) || {}

  const lines: string[] = [
    '-- Project Zomboid Sandbox Configuration',
    `-- Profile: ${profile.name}`,
    '-- Generated by PZ Server Manager',
    '',
    'SandboxVars = {',
  ]

  for (const [key, value] of Object.entries(settings)) {
    if (key === 'ZombieConfig') continue
    if (value === null || value === undefined) continue
    if (typeof value === 'boolean') lines.push(`    ${key} = ${value},`)
    else if (typeof value === 'number') lines.push(`    ${key} = ${value},`)
    else lines.push(`    ${key} = "${value}",`)
  }

  lines.push('    ZombieConfig = {')
  for (const [key, value] of Object.entries(zombieConfig)) {
    if (value === null || value === undefined) continue
    if (typeof value === 'boolean') lines.push(`        ${key} = ${value},`)
    else if (typeof value === 'number') lines.push(`        ${key} = ${value},`)
    else lines.push(`        ${key} = "${value}",`)
  }
  lines.push('    },')
  lines.push('}')

  writeFileSync(luaPath, lines.join('\n') + '\n', 'utf-8')
}

// ---------------------------------------------------------------------------
// Find the PID of the java.exe process that owns our server
// ---------------------------------------------------------------------------
function findServerPid(serverName: string): Promise<number | null> {
  return new Promise((resolve) => {
    exec(
      `wmic process where "name='java.exe'" get ProcessId,CommandLine /format:csv`,
      { timeout: 8000 },
      (err, stdout) => {
        if (err || !stdout) return resolve(null)
        const lines = stdout.split('\n')
        for (const line of lines) {
          if (line.includes(`-servername`) && line.includes(serverName)) {
            const parts = line.trim().split(',')
            const pid = parseInt(parts[parts.length - 1], 10)
            if (!isNaN(pid)) return resolve(pid)
          }
        }
        resolve(null)
      }
    )
  })
}

function isPidAlive(pid: number): Promise<boolean> {
  return new Promise((resolve) => {
    exec(`tasklist /FI "PID eq ${pid}" /NH`, { timeout: 5000 }, (err, stdout) => {
      if (err) return resolve(false)
      resolve(stdout.includes(String(pid)))
    })
  })
}

function killProcessTree(pid: number): Promise<void> {
  return new Promise((resolve) => {
    exec(`taskkill /PID ${pid} /T /F`, { timeout: 10000 }, () => resolve())
  })
}

export function setupServerHandlers(mainWindow: BrowserWindow | null) {
  mainWindowRef = mainWindow

  ipcMain.handle('server:start', async (_event, profileId: string) => {
    try {
      if (runningServers.has(profileId)) {
        const srv = runningServers.get(profileId)!
        if (srv.status === 'running' || srv.status === 'starting') {
          return { success: false, message: 'Server is already running' }
        }
      }

      const profile = await getProfile(profileId)
      if (!profile) return { success: false, message: 'Profile not found' }

      const serverDir = profile.serverInstallPath
      const startBat = join(serverDir, 'StartServer64.bat')

      if (!existsSync(startBat)) {
        return { success: false, message: 'Server files not found. Please verify the Server Install Path in Server Config.' }
      }

      const serverName = profile.name.replace(/[^a-zA-Z0-9_-]/g, '_')
      const adminPassword = profile.adminPassword || 'admin'
      const dataPath = resolveDataPath(profile.worldSavePath)

      // -----------------------------------------------------------------------
      // Write config files ONLY when launchMode is 'managed' (the default).
      // In 'passthrough' mode the user edits files directly and the app must
      // NOT overwrite them.
      // -----------------------------------------------------------------------
      const launchMode = profile.launchMode || 'managed'
      emitConsoleOutput(profileId, `[PZ Manager] Launch mode: ${launchMode}`)
      emitConsoleOutput(profileId, `[PZ Manager] Data path: ${dataPath}`)

      if (launchMode === 'managed') {
        emitConsoleOutput(profileId, `[PZ Manager] Writing config files for profile "${serverName}"...`)
        try {
          writeProfileIni(serverName, dataPath, profile)
          emitConsoleOutput(profileId, `[PZ Manager] ✓ Wrote ${serverName}.ini`)
        } catch (e) {
          const msg = e instanceof Error ? e.message : String(e)
          emitConsoleOutput(profileId, `[PZ Manager] ⚠ Failed to write INI: ${msg}`)
        }
        try {
          writeProfileSandbox(serverName, dataPath, profile)
          emitConsoleOutput(profileId, `[PZ Manager] ✓ Wrote ${serverName}_SandboxVars.lua`)
        } catch (e) {
          const msg = e instanceof Error ? e.message : String(e)
          emitConsoleOutput(profileId, `[PZ Manager] ⚠ Failed to write SandboxVars: ${msg}`)
        }
      } else {
        emitConsoleOutput(profileId, `[PZ Manager] Passthrough mode — using existing config files as-is (not overwriting)`)
        emitConsoleOutput(profileId, `[PZ Manager] Config: ${dataPath}\\Server\\${serverName}.ini`)
      }

      // -----------------------------------------------------------------------
      // Write the launcher batch file and open it in a new visible console window
      // -----------------------------------------------------------------------
      const launcherPath = join(serverDir, `_pzm_launch_${serverName}.bat`)

      // Build the -cachedir argument to point PZ at the correct data directory
      // so it reads OUR named config files, not the default Zomboid folder
      const cacheArg = dataPath !== resolveDataPath() ? `-cachedir "${dataPath}"` : ''

      const launcherContent = [
        `@echo off`,
        `title PZ Server - ${serverName}`,
        `cd /d "${serverDir}"`,
        `echo ================================================`,
        `echo  Project Zomboid Server: ${serverName}`,
        `echo  Profile: ${profile.name}`,
        `echo  Port: ${profile.port}`,
        `echo  Mods: ${profile.mods.length}`,
        `echo ================================================`,
        `echo.`,
        `call StartServer64.bat -servername "${serverName}" -adminpassword "${adminPassword}"${cacheArg ? ' ' + cacheArg : ''}`,
        `echo.`,
        `echo ============================================`,
        `echo  Server stopped. You may close this window.`,
        `echo ============================================`,
        `pause`,
      ].join('\r\n')

      writeFileSync(launcherPath, launcherContent)

      const proc: ChildProcess = spawn(
        'cmd.exe',
        ['/c', 'start', `"PZ Server - ${serverName}"`, '/D', serverDir, launcherPath],
        {
          cwd: serverDir,
          detached: true,
          stdio: 'ignore',
          shell: false,
        }
      )
      proc.unref()

      const serverEntry: ServerProcess = {
        watcher: null,
        pid: null,
        status: 'starting',
        startTime: new Date(),
        serverName,
        serverDir,
      }
      runningServers.set(profileId, serverEntry)
      emitStatusChange(profileId, 'starting')
      emitConsoleOutput(profileId, `[PZ Manager] Server console window opened. Waiting for Java process...`)
      emitConsoleOutput(profileId, `[PZ Manager] Config: ${dataPath}\\Server\\${serverName}.ini`)

      // Poll for the java.exe PID
      let attempts = 0
      const maxAttempts = 30

      const pollForPid = async () => {
        attempts++
        const pid = await findServerPid(serverName)
        if (pid) {
          serverEntry.pid = pid
          serverEntry.status = 'running'
          emitStatusChange(profileId, 'running')
          emitConsoleOutput(profileId, `[PZ Manager] Server process detected (PID ${pid}). Server is running!`)

          serverEntry.watcher = setInterval(async () => {
            if (!serverEntry.pid) return
            const alive = await isPidAlive(serverEntry.pid)
            if (!alive) {
              emitConsoleOutput(profileId, `[PZ Manager] Server process (PID ${serverEntry.pid}) has stopped.`)
              if (serverEntry.watcher) clearInterval(serverEntry.watcher)
              runningServers.delete(profileId)
              emitStatusChange(profileId, 'stopped')
            }
          }, 5000)

        } else if (attempts < maxAttempts) {
          setTimeout(pollForPid, 2000)
        } else {
          emitConsoleOutput(profileId, `[PZ Manager] Could not detect server process after 60s. Check the console window for errors.`)
          runningServers.delete(profileId)
          emitStatusChange(profileId, 'stopped')
        }
      }

      setTimeout(pollForPid, 3000)

      return { success: true, message: `Server "${serverName}" launching...` }
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : String(error)
      return { success: false, message: msg }
    }
  })

  ipcMain.handle('server:stop', async (_event, profileId: string) => {
    const srv = runningServers.get(profileId)
    if (!srv) return { success: false, message: 'Server is not running' }

    try {
      srv.status = 'stopping'
      emitStatusChange(profileId, 'stopping')
      emitConsoleOutput(profileId, `[PZ Manager] Stopping server "${srv.serverName}"...`)

      if (srv.pid) {
        emitConsoleOutput(profileId, `[PZ Manager] Sending stop signal to PID ${srv.pid}...`)

        await new Promise<void>((resolve) => {
          exec(
            `powershell -Command "& {$wshell = New-Object -ComObject wscript.shell; $wshell.AppActivate('PZ Server - ${srv.serverName}'); Start-Sleep -Milliseconds 200; $wshell.SendKeys('quit{ENTER}')}"`,
            { timeout: 5000 },
            () => resolve()
          )
        })

        let waited = 0
        while (waited < 30000) {
          await new Promise(resolve => setTimeout(resolve, 2000))
          waited += 2000
          const alive = await isPidAlive(srv.pid)
          if (!alive) {
            emitConsoleOutput(profileId, `[PZ Manager] Server stopped gracefully.`)
            break
          }
        }

        const stillAlive = await isPidAlive(srv.pid)
        if (stillAlive) {
          emitConsoleOutput(profileId, `[PZ Manager] Force-stopping server...`)
          await killProcessTree(srv.pid)
        }
      }

      if (srv.watcher) clearInterval(srv.watcher)
      runningServers.delete(profileId)
      emitStatusChange(profileId, 'stopped')

      return { success: true, message: 'Server stopped.' }
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : String(error)
      return { success: false, message: msg }
    }
  })

  ipcMain.handle('server:restart', async (_event, profileId: string) => {
    const srv = runningServers.get(profileId)
    if (srv && srv.pid) {
      if (srv.watcher) clearInterval(srv.watcher)
      emitConsoleOutput(profileId, `[PZ Manager] Restarting server...`)
      await killProcessTree(srv.pid)
      runningServers.delete(profileId)
      emitStatusChange(profileId, 'stopped')
      await new Promise(resolve => setTimeout(resolve, 2000))
    }
    return ipcMain.emit('server:start', { sender: mainWindowRef?.webContents }, profileId)
  })

  ipcMain.handle('server:getStatus', async (_event, profileId: string) => {
    const srv = runningServers.get(profileId)
    return srv ? srv.status : 'stopped'
  })

  ipcMain.handle('server:getAllStatuses', async () => {
    const statuses: Record<string, string> = {}
    runningServers.forEach((srv, id) => {
      statuses[id] = srv.status
    })
    return statuses
  })

  ipcMain.handle('server:sendCommand', async (_event, profileId: string, command: string) => {
    const srv = runningServers.get(profileId)
    if (!srv || !srv.pid) {
      return { success: false, message: 'Server is not running' }
    }
    emitConsoleOutput(profileId, `[PZ Manager] Sending command: ${command}`)
    await new Promise<void>((resolve) => {
      exec(
        `powershell -Command "& {$wshell = New-Object -ComObject wscript.shell; $wshell.AppActivate('PZ Server - ${srv.serverName}'); Start-Sleep -Milliseconds 100; $wshell.SendKeys('${command.replace(/'/g, "''")}'); $wshell.SendKeys('{ENTER}')}"`,
        { timeout: 5000 },
        () => resolve()
      )
    })
    return { success: true }
  })
}

function emitConsoleOutput(profileId: string, line: string) {
  if (mainWindowRef && !mainWindowRef.isDestroyed()) {
    mainWindowRef.webContents.send(`server:console:${profileId}`, line)
  }
}

function emitStatusChange(profileId: string, status: string) {
  if (mainWindowRef && !mainWindowRef.isDestroyed()) {
    mainWindowRef.webContents.send('server:statusChange', profileId, status)
  }
}
